//! Mempool monitor — head-start on Venus oracle price updates.
//!
//! Subscribes to the chain's pending-tx stream, looks up the full
//! transaction for each hash, and filters for calls that target the
//! Venus price oracle discovered by
//! [`VenusAdapter`](charon_protocols::venus::VenusAdapter). A match
//! means the next block is about to carry a price change that could
//! push borrowers under water; decoded [`OracleUpdate`] events are
//! emitted on an `mpsc` channel so a downstream handler can simulate
//! the impact and pre-sign liquidations before the update confirms.
//!
//! The monitor also owns a small in-memory `DashMap` of pre-signed
//! liquidations keyed by borrower. On the next
//! [`ChainEvent::NewBlock`](crate::listener::ChainEvent::NewBlock) the
//! caller drains this map via [`MempoolMonitor::drain`], broadcasts the
//! raw txs, and the monitor clears its state — mempool pre-signs are
//! valid for exactly one block. Entries older than
//! `max_pending_age_secs` are dropped silently on drain; they represent
//! an oracle update we saw but never confirmed.
//!
//! Pure decode + pre-sign storage lives on [`PendingCache`] so tests
//! can exercise it without a live RPC; the RPC-bound subscription
//! lives on [`MempoolMonitor`].
//!
//! This module is library-only. Wiring into the CLI listen loop is a
//! separate PR once real signer + deployed liquidator are in place.

use std::collections::HashSet;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use alloy::consensus::Transaction as _;
use alloy::primitives::{Address, B256, Bytes, FixedBytes, U256};
use alloy::providers::Provider;
use alloy::providers::RootProvider;
use alloy::pubsub::PubSubFrontend;
use alloy::sol;
use alloy::sol_types::SolCall;
use anyhow::{Context, Result};
use charon_core::LiquidationOpportunity;
use dashmap::DashMap;
use futures_util::StreamExt;
use tokio::sync::mpsc;
use tracing::{debug, info, warn};

/// Default lifetime for a pre-signed liquidation sitting in the
/// pending map. The head-start window is ~3 s on BSC (one block); we
/// pad to 30 s so a one-block stall on the private RPC doesn't
/// silently drop a prepared tx.
pub const DEFAULT_MAX_PENDING_AGE: Duration = Duration::from_secs(30);

sol! {
    /// Superset of price-update surfaces the Venus oracle stack has
    /// exposed historically. Kept in one `sol!` block so each call's
    /// `::SELECTOR` constant is generated by alloy — no hand-maintained
    /// keccak tables.
    interface IVenusOracleWrite {
        /// Resilient oracle — refreshes the cached snapshot for `asset`
        /// by re-reading its configured source oracles.
        function updatePrice(address asset) external;

        /// Alternate entry on the resilient oracle for the same action.
        function updateAssetPrice(address asset) external;

        /// Legacy oracle — writes a price directly against the
        /// underlying asset address.
        function setDirectPrice(address asset, uint256 price) external;

        /// Older Compound-style oracle — writes a price keyed by
        /// vToken.
        function setUnderlyingPrice(address vToken, uint256 price) external;
    }
}

/// Decoded observation extracted from one pending tx.
#[derive(Debug, Clone)]
pub struct OracleUpdate {
    /// Hash of the pending tx that triggered the observation.
    pub tx_hash: B256,
    /// The 4-byte selector matched. Callers key their simulation paths
    /// off this — single-arg selectors carry no price, two-arg
    /// selectors carry the new on-chain price.
    pub selector: FixedBytes<4>,
    /// Address argument from the call (asset or vToken, depending on
    /// the selector).
    pub asset: Address,
    /// New price, if the selector carried one. `None` for
    /// `updatePrice` / `updateAssetPrice` — the caller must re-read
    /// the oracle after the tx confirms (or simulate via the
    /// underlying feed).
    pub new_price: Option<U256>,
}

/// One signed liquidation sitting in the pending map, ready to
/// broadcast the moment the next block lands.
#[derive(Debug, Clone)]
pub struct PreSignedLiquidation {
    /// Borrower targeted. Also the map key; duplicated here so a
    /// drained `Vec<PreSignedLiquidation>` is self-describing.
    pub borrower: Address,
    /// Raw EIP-2718 envelope bytes, as produced by
    /// [`TxBuilder::sign`](charon_executor::TxBuilder::sign). Ready
    /// for `eth_sendRawTransaction`.
    pub raw_tx: Bytes,
    /// The opportunity this tx was built against. Carried so the
    /// drainer can log context and re-rank if multiple pre-signs
    /// target the same borrower across different oracle updates.
    pub opportunity: LiquidationOpportunity,
    /// Hash of the pending oracle tx that motivated this pre-sign.
    pub trigger_tx: B256,
    /// Unix seconds at which the entry was inserted.
    pub inserted_at: u64,
}

/// Pure decode + pre-sign storage. Separated from the RPC layer so
/// tests can exercise the selector logic and TTL semantics without
/// opening a socket.
///
/// Holds the chain's short name so the mempool metrics (#300) can
/// be labelled with the same `chain` key the scanner and gas oracle
/// use. Default constructors fall back to `"unknown"` rather than
/// refusing construction — unit tests for the decoder don't care,
/// and production call sites always pass an explicit name.
#[derive(Debug)]
pub struct PendingCache {
    chain: String,
    oracle: Address,
    selectors: HashSet<FixedBytes<4>>,
    pending: DashMap<Address, PreSignedLiquidation>,
    max_pending_age_secs: u64,
}

impl PendingCache {
    pub fn new(
        chain: impl Into<String>,
        oracle: Address,
        selectors: HashSet<FixedBytes<4>>,
        max_pending_age: Duration,
    ) -> Self {
        Self {
            chain: chain.into(),
            oracle,
            selectors,
            pending: DashMap::new(),
            max_pending_age_secs: max_pending_age.as_secs(),
        }
    }

    pub fn with_defaults(oracle: Address) -> Self {
        Self::new("unknown", oracle, default_selectors(), DEFAULT_MAX_PENDING_AGE)
    }

    pub fn oracle(&self) -> Address {
        self.oracle
    }

    /// Chain label the cache emits with on every mempool metric.
    pub fn chain(&self) -> &str {
        &self.chain
    }

    pub fn is_tracked_selector(&self, selector: FixedBytes<4>) -> bool {
        self.selectors.contains(&selector)
    }

    /// Insert a freshly pre-signed liquidation. Overwrites any prior
    /// entry for the same borrower — the most recent oracle update
    /// wins, which is what we want when two updates land in the same
    /// block window (the later one is what the chain will see).
    ///
    /// Refreshes the
    /// [`charon_mempool_pending_oracle_updates`](charon_metrics::names::MEMPOOL_PENDING_ORACLE_UPDATES)
    /// gauge so dashboards track the live cache size even between
    /// block-boundary drains. Issue #300.
    pub fn insert(&self, tx: PreSignedLiquidation) {
        debug!(
            borrower = %tx.borrower,
            trigger = %tx.trigger_tx,
            "pre-signed liquidation armed"
        );
        self.pending.insert(tx.borrower, tx);
        charon_metrics::set_mempool_pending_oracle_updates(
            &self.chain,
            self.pending.len() as u64,
        );
    }

    pub fn pending_len(&self) -> usize {
        self.pending.len()
    }

    pub fn is_empty(&self) -> bool {
        self.pending.is_empty()
    }

    /// Take every entry out of the pending map and drop any that are
    /// older than `max_pending_age_secs`. Called by the block-listener
    /// task on each `NewBlock` event — pre-signs only live for one
    /// block window, so anything that didn't fire is stale.
    ///
    /// Increments
    /// [`charon_mempool_drained_total`](charon_metrics::names::MEMPOOL_DRAINED_TOTAL)
    /// by the number of fresh entries drained and zeroes the
    /// [`charon_mempool_pending_oracle_updates`](charon_metrics::names::MEMPOOL_PENDING_ORACLE_UPDATES)
    /// gauge — the cache is empty after a drain. Issue #300.
    pub fn drain(&self) -> Vec<PreSignedLiquidation> {
        let now = unix_now();
        let max_age = self.max_pending_age_secs;
        let mut out = Vec::with_capacity(self.pending.len());
        let keys: Vec<Address> = self.pending.iter().map(|e| *e.key()).collect();
        for k in keys {
            if let Some((_, entry)) = self.pending.remove(&k) {
                if now.saturating_sub(entry.inserted_at) > max_age {
                    warn!(
                        borrower = %entry.borrower,
                        age_secs = now.saturating_sub(entry.inserted_at),
                        "dropped stale pre-signed liquidation"
                    );
                    continue;
                }
                out.push(entry);
            }
        }
        debug!(drained = out.len(), "mempool cache drained");
        charon_metrics::record_mempool_drained(&self.chain, out.len() as u64);
        charon_metrics::set_mempool_pending_oracle_updates(
            &self.chain,
            self.pending.len() as u64,
        );
        out
    }

    /// Pure decoder — returns `None` when the recipient isn't the
    /// bound oracle, the selector isn't tracked, or the calldata
    /// fails to decode against every candidate shape.
    pub fn decode(&self, tx_hash: B256, to: Option<Address>, input: &[u8]) -> Option<OracleUpdate> {
        if to != Some(self.oracle) {
            return None;
        }
        if input.len() < 4 {
            return None;
        }
        let selector = FixedBytes::<4>::from_slice(&input[..4]);
        if !self.selectors.contains(&selector) {
            return None;
        }
        decode_oracle_call(tx_hash, selector, input)
    }
}

/// Subscribes to the pending-tx stream, filters oracle updates, and
/// holds pre-signed liquidations until the next block.
///
/// Cheap to clone — all mutable state lives behind `Arc` / `DashMap`.
/// Clone into the block-listener task so it can call
/// [`MempoolMonitor::drain`] without coordinating with the mempool
/// task.
#[derive(Clone)]
pub struct MempoolMonitor {
    provider: Arc<RootProvider<PubSubFrontend>>,
    cache: Arc<PendingCache>,
}

impl MempoolMonitor {
    /// Full-control constructor. `chain` is the short chain name the
    /// mempool metrics (#300) emit as a `chain` label.
    pub fn new(
        chain: impl Into<String>,
        provider: Arc<RootProvider<PubSubFrontend>>,
        oracle: Address,
        selectors: HashSet<FixedBytes<4>>,
        max_pending_age: Duration,
    ) -> Self {
        Self {
            provider,
            cache: Arc::new(PendingCache::new(
                chain,
                oracle,
                selectors,
                max_pending_age,
            )),
        }
    }

    /// Convenience: build with [`default_selectors`] and
    /// [`DEFAULT_MAX_PENDING_AGE`].
    pub fn with_defaults(
        chain: impl Into<String>,
        provider: Arc<RootProvider<PubSubFrontend>>,
        oracle: Address,
    ) -> Self {
        Self::new(
            chain,
            provider,
            oracle,
            default_selectors(),
            DEFAULT_MAX_PENDING_AGE,
        )
    }

    pub fn oracle(&self) -> Address {
        self.cache.oracle()
    }

    /// Chain label this monitor emits with.
    pub fn chain(&self) -> &str {
        self.cache.chain()
    }

    /// Share the inner cache. Lets the block-listener task call
    /// [`PendingCache::drain`] without going through the monitor,
    /// which keeps its `run` loop free to stay on the pending-tx
    /// stream.
    pub fn cache(&self) -> Arc<PendingCache> {
        self.cache.clone()
    }

    pub fn insert(&self, tx: PreSignedLiquidation) {
        self.cache.insert(tx);
    }

    pub fn drain(&self) -> Vec<PreSignedLiquidation> {
        self.cache.drain()
    }

    pub fn pending_len(&self) -> usize {
        self.cache.pending_len()
    }

    /// Run the pending-tx subscription forever. Reconnect on stream
    /// error with the same 1 s → 30 s exponential backoff as
    /// [`BlockListener`](crate::listener::BlockListener).
    ///
    /// Emits one [`OracleUpdate`] per matched tx on `tx`. Returns
    /// `Ok(())` only when the receiver is dropped — the loop is
    /// expected to run for the lifetime of the process.
    ///
    /// Every reconnect attempt bumps
    /// [`charon_mempool_websocket_reconnects_total`](charon_metrics::names::MEMPOOL_WS_RECONNECTS_TOTAL)
    /// (issue #300) and
    /// [`charon_rpc_connection_reconnects_total`](charon_metrics::names::RPC_RECONNECTS_TOTAL)
    /// under `endpoint_kind="public"` (issue #302). Both land on the
    /// same operator dashboard — the per-chain mempool counter is
    /// the actionable signal; the generic RPC reconnect counter
    /// aggregates across every pubsub call site for a quick
    /// "is upstream degrading?" read.
    pub async fn run(&self, tx: mpsc::Sender<OracleUpdate>) -> Result<()> {
        let mut backoff = Duration::from_secs(1);
        loop {
            match self.run_once(&tx).await {
                Ok(()) => {
                    info!(oracle = %self.oracle(), "mempool channel closed, exiting");
                    return Ok(());
                }
                Err(err) => {
                    charon_metrics::record_mempool_ws_reconnect(self.chain());
                    charon_metrics::record_rpc_reconnect(
                        charon_metrics::endpoint_kind::PUBLIC,
                    );
                    warn!(
                        oracle = %self.oracle(),
                        error = ?err,
                        backoff_secs = backoff.as_secs(),
                        "mempool subscription error, reconnecting after backoff"
                    );
                    tokio::time::sleep(backoff).await;
                    backoff = (backoff * 2).min(Duration::from_secs(30));
                }
            }
        }
    }

    async fn run_once(&self, tx: &mpsc::Sender<OracleUpdate>) -> Result<()> {
        let sub = self
            .provider
            .subscribe_pending_transactions()
            .await
            .context("mempool: subscribe_pending_transactions failed")?;

        info!(oracle = %self.oracle(), "pending-tx subscription established");

        let mut stream = sub.into_stream();
        while let Some(hash) = stream.next().await {
            // Lookup failures are common for txs that dropped out of
            // the pool between the hash push and our get — log at
            // debug, keep going. `time_rpc` instruments the per-call
            // latency (issue #302); the `connection_lost` / transport
            // failure branch is classified by `record_rpc_error`
            // below so timeouts vs dropped txs stay separable in
            // the dashboard.
            let full = match charon_metrics::time_rpc(
                charon_metrics::rpc_method::ETH_GET_TRANSACTION_BY_HASH,
                charon_metrics::endpoint_kind::PUBLIC,
                async { self.provider.get_transaction_by_hash(hash).await },
            )
            .await
            {
                Ok(Some(t)) => t,
                Ok(None) => {
                    debug!(%hash, "pending tx vanished before fetch");
                    continue;
                }
                Err(err) => {
                    charon_metrics::record_rpc_error(
                        charon_metrics::rpc_method::ETH_GET_TRANSACTION_BY_HASH,
                        charon_metrics::rpc_error::CONNECTION_LOST,
                    );
                    debug!(%hash, ?err, "get_transaction_by_hash failed");
                    continue;
                }
            };

            let to = full.inner.kind().to().copied();
            let input = full.inner.input();
            let Some(update) = self.cache.decode(hash, to, input) else {
                continue;
            };

            info!(
                %hash,
                asset = %update.asset,
                selector = %format_selector(update.selector),
                price = ?update.new_price,
                "venus oracle update seen in mempool"
            );

            if tx.send(update).await.is_err() {
                return Ok(());
            }
        }

        anyhow::bail!("mempool: pending-tx subscription stream ended")
    }
}

/// The four Venus oracle write selectors this module recognises by
/// default. Callers can override via [`MempoolMonitor::new`] — for
/// example to track a chain-specific proxy that exposes a different
/// setter name.
pub fn default_selectors() -> HashSet<FixedBytes<4>> {
    let mut s = HashSet::with_capacity(4);
    s.insert(IVenusOracleWrite::updatePriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::updateAssetPriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::setDirectPriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::setUnderlyingPriceCall::SELECTOR.into());
    s
}

fn decode_oracle_call(
    tx_hash: B256,
    selector: FixedBytes<4>,
    input: &[u8],
) -> Option<OracleUpdate> {
    // `abi_decode_raw` skips the selector and validates the body.
    // `validate = true` rejects trailing junk.
    let body = &input[4..];

    if selector == FixedBytes::<4>::from(IVenusOracleWrite::updatePriceCall::SELECTOR) {
        let call = IVenusOracleWrite::updatePriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: None,
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::updateAssetPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::updateAssetPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: None,
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::setDirectPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::setDirectPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: Some(call.price),
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::setUnderlyingPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::setUnderlyingPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.vToken,
            new_price: Some(call.price),
        });
    }
    None
}

fn format_selector(sel: FixedBytes<4>) -> String {
    let b = sel.as_slice();
    format!("0x{:02x}{:02x}{:02x}{:02x}", b[0], b[1], b[2], b[3])
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::{address, b256};
    use alloy::sol_types::SolCall;
    use charon_core::{FlashLoanSource, Position, ProtocolId, SwapRoute};

    const ORACLE: Address = address!("1111111111111111111111111111111111111111");
    const OTHER: Address = address!("2222222222222222222222222222222222222222");
    const ASSET: Address = address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    const HASH: B256 = b256!("abababababababababababababababababababababababababababababababab");

    fn mk_cache() -> PendingCache {
        PendingCache::with_defaults(ORACLE)
    }

    fn mk_opp() -> LiquidationOpportunity {
        LiquidationOpportunity {
            position: Position {
                protocol: ProtocolId::Venus,
                chain_id: 56,
                borrower: address!("3333333333333333333333333333333333333333"),
                collateral_token: address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
                debt_token: address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
                collateral_amount: U256::from(1_000u64),
                debt_amount: U256::from(500u64),
                health_factor: U256::ZERO,
                liquidation_bonus_bps: 1_000,
            },
            debt_to_repay: U256::from(250u64),
            expected_collateral_out: U256::from(275u64),
            flash_source: FlashLoanSource::AaveV3,
            swap_route: SwapRoute {
                token_in: address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
                token_out: address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
                amount_in: U256::from(275u64),
                min_amount_out: U256::from(260u64),
                pool_fee: 3_000,
            },
            net_profit_usd_cents: 5_000,
        }
    }

    #[test]
    fn default_selectors_has_four_entries() {
        assert_eq!(default_selectors().len(), 4);
    }

    #[test]
    fn decode_update_price_yields_asset_without_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updatePriceCall { asset: ASSET };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert!(out.new_price.is_none());
        assert_eq!(out.tx_hash, HASH);
    }

    #[test]
    fn decode_update_asset_price_yields_asset_without_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updateAssetPriceCall { asset: ASSET };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert!(out.new_price.is_none());
    }

    #[test]
    fn decode_set_direct_price_carries_new_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::setDirectPriceCall {
            asset: ASSET,
            price: U256::from(12_345u64),
        };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert_eq!(out.new_price, Some(U256::from(12_345u64)));
    }

    #[test]
    fn decode_set_underlying_price_carries_vtoken_and_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::setUnderlyingPriceCall {
            vToken: ASSET,
            price: U256::from(99u64),
        };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert_eq!(out.new_price, Some(U256::from(99u64)));
    }

    #[test]
    fn decode_rejects_wrong_recipient() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updatePriceCall { asset: ASSET };
        let data = call.abi_encode();
        assert!(c.decode(HASH, Some(OTHER), &data).is_none());
        assert!(c.decode(HASH, None, &data).is_none());
    }

    #[test]
    fn decode_rejects_unknown_selector() {
        let c = mk_cache();
        // `transfer(address,uint256)` selector — not in the tracked
        // set. Followed by two zero-padded words so a lenient decoder
        // wouldn't accidentally accept it.
        let mut data = vec![0xa9, 0x05, 0x9c, 0xbb];
        data.extend_from_slice(&[0u8; 64]);
        assert!(c.decode(HASH, Some(ORACLE), &data).is_none());
    }

    #[test]
    fn decode_rejects_short_input() {
        let c = mk_cache();
        assert!(c.decode(HASH, Some(ORACLE), &[]).is_none());
        assert!(c.decode(HASH, Some(ORACLE), &[0xde, 0xad]).is_none());
    }

    #[test]
    fn decode_rejects_truncated_calldata() {
        let c = mk_cache();
        let sel: [u8; 4] = IVenusOracleWrite::updatePriceCall::SELECTOR;
        assert!(c.decode(HASH, Some(ORACLE), &sel).is_none());
    }

    #[test]
    fn insert_and_drain_roundtrips() {
        let c = mk_cache();
        let opp = mk_opp();
        let borrower = opp.position.borrower;
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x01, 0x02, 0x03]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert_eq!(drained.len(), 1);
        assert_eq!(drained[0].borrower, borrower);
        assert_eq!(c.pending_len(), 0);
        // Second drain yields nothing.
        assert!(c.drain().is_empty());
    }

    #[test]
    fn drain_drops_stale_entries() {
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::new(),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now().saturating_sub(3_600),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert!(drained.is_empty(), "stale entry should be dropped");
        assert_eq!(c.pending_len(), 0);
    }

    #[test]
    fn insert_overwrites_same_borrower() {
        let c = mk_cache();
        let opp = mk_opp();
        let borrower = opp.position.borrower;
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x01]),
            opportunity: opp.clone(),
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x02]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert_eq!(drained.len(), 1);
        assert_eq!(drained[0].raw_tx.as_ref(), &[0x02]);
    }

    #[test]
    fn is_tracked_selector_matches_defaults() {
        let c = mk_cache();
        let sel = FixedBytes::<4>::from(IVenusOracleWrite::updatePriceCall::SELECTOR);
        assert!(c.is_tracked_selector(sel));
        let unknown = FixedBytes::<4>::from([0xde, 0xad, 0xbe, 0xef]);
        assert!(!c.is_tracked_selector(unknown));
    }

    #[test]
    fn oracle_round_trips() {
        let c = mk_cache();
        assert_eq!(c.oracle(), ORACLE);
    }

    #[test]
    fn format_selector_renders_lowercase_hex() {
        let sel = FixedBytes::<4>::from([0xab, 0xcd, 0xef, 0x01]);
        assert_eq!(format_selector(sel), "0xabcdef01");
    }
}
