//! Mempool monitor — head-start on Venus oracle price updates.
//!
//! Subscribes to the chain's pending-tx stream, looks up the full
//! transaction for each hash, and filters for calls that target the
//! Venus price oracle discovered by
//! [`VenusAdapter`](charon_protocols::venus::VenusAdapter). A match
//! means the next block is about to carry a price change that could
//! push borrowers under water; decoded [`OracleUpdate`] events are
//! emitted on an `mpsc` channel so a downstream handler can simulate
//! the impact and pre-sign liquidations before the update confirms.
//!
//! The monitor also owns a small in-memory `DashMap` of pre-signed
//! liquidations keyed by borrower. On the next
//! [`ChainEvent::NewBlock`](crate::listener::ChainEvent::NewBlock) the
//! caller drains this map via [`MempoolMonitor::drain`], broadcasts the
//! raw txs, and the monitor clears its state — mempool pre-signs are
//! valid for exactly one block. Entries older than
//! `max_pending_age_secs` are dropped silently on drain; they represent
//! an oracle update we saw but never confirmed.
//!
//! Pure decode + pre-sign storage lives on [`PendingCache`] so tests
//! can exercise it without a live RPC; the RPC-bound subscription
//! lives on [`MempoolMonitor`].
//!
//! # RPC endpoint requirements
//!
//! **Public BSC RPCs do not feed this module.** `eth_subscribe` for
//! `newPendingTransactions` is either disabled or returns only the
//! local-node pool on every public BSC endpoint (Binance public WS,
//! Ankr, Allnodes, QuickNode shared tier, publicnode). The ~3 s
//! head-start the monitor is designed for is only achievable with:
//!
//! - a paid MEV-streaming service (bloxroute, blocknative), or
//! - a self-hosted BSC geth with the full txpool exposed.
//!
//! When the configured endpoint only streams local-pool transactions,
//! `run_once` still succeeds (subscription establishes) but zero
//! [`OracleUpdate`] events ever arrive. The monitor guards against a
//! silent-nothing scenario by logging a `warn!` with the endpoint URL
//! when no pending tx is observed within
//! [`FIRST_TX_WATCHDOG`] of subscription — operators see an explicit
//! "subscription appears inactive" signal instead of a blank stream.
//!
//! # Safety invariant
//!
//! Pre-signed liquidations bypass the `eth_call` simulation gate that
//! `charon-executor` would otherwise enforce before broadcast. The
//! cache therefore returns pre-signs wrapped in
//! [`UnverifiedPreSigned`] on drain — the raw EIP-2718 envelope is
//! only reachable after a caller presents a [`SimulationVerdict::Ok`]
//! via [`UnverifiedPreSigned::verify`]. A broadcaster written against
//! this type cannot skip the gate without disabling the type system.
//!
//! This module is library-only. Wiring into the CLI listen loop is a
//! separate PR once real signer + deployed liquidator are in place.

use std::collections::HashSet;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use alloy::consensus::Transaction as _;
use alloy::primitives::{Address, B256, Bytes, FixedBytes, U256};
use alloy::providers::Provider;
use alloy::providers::RootProvider;
use alloy::pubsub::PubSubFrontend;
use alloy::sol;
use alloy::sol_types::SolCall;
use anyhow::{Context, Result};
use charon_core::LiquidationOpportunity;
use dashmap::DashMap;
use futures_util::StreamExt;
use tokio::sync::mpsc;
use tracing::{debug, info, warn};

/// Default lifetime for a pre-signed liquidation sitting in the
/// pending map. The head-start window is ~3 s on BSC (one block); we
/// pad to 30 s so a one-block stall on the private RPC doesn't
/// silently drop a prepared tx.
pub const DEFAULT_MAX_PENDING_AGE: Duration = Duration::from_secs(30);

/// Grace period after `subscribe_pending_transactions` succeeds before
/// the monitor starts complaining that nothing is arriving. Long enough
/// to cover a quiet market window on a healthy mempool stream (BSC
/// steady-state pending tx rate is dozens-per-second), short enough
/// that an operator pointed at a public RPC that silently drops
/// pending-tx subscriptions sees a warning within a minute.
pub const FIRST_TX_WATCHDOG: Duration = Duration::from_secs(30);

sol! {
    /// Superset of price-update surfaces the Venus oracle stack has
    /// exposed historically. Kept in one `sol!` block so each call's
    /// `::SELECTOR` constant is generated by alloy — no hand-maintained
    /// keccak tables.
    interface IVenusOracleWrite {
        /// Resilient oracle — refreshes the cached snapshot for `asset`
        /// by re-reading its configured source oracles.
        function updatePrice(address asset) external;

        /// Alternate entry on the resilient oracle for the same action.
        function updateAssetPrice(address asset) external;

        /// Legacy oracle — writes a price directly against the
        /// underlying asset address.
        function setDirectPrice(address asset, uint256 price) external;

        /// Older Compound-style oracle — writes a price keyed by
        /// vToken.
        function setUnderlyingPrice(address vToken, uint256 price) external;
    }
}

/// Decoded observation extracted from one pending tx.
#[derive(Debug, Clone)]
pub struct OracleUpdate {
    /// Hash of the pending tx that triggered the observation.
    pub tx_hash: B256,
    /// The 4-byte selector matched. Callers key their simulation paths
    /// off this — single-arg selectors carry no price, two-arg
    /// selectors carry the new on-chain price.
    pub selector: FixedBytes<4>,
    /// Address argument from the call (asset or vToken, depending on
    /// the selector).
    pub asset: Address,
    /// New price, if the selector carried one. `None` for
    /// `updatePrice` / `updateAssetPrice` — the caller must re-read
    /// the oracle after the tx confirms (or simulate via the
    /// underlying feed).
    pub new_price: Option<U256>,
}

/// One signed liquidation sitting in the pending map, ready to
/// broadcast the moment the next block lands.
///
/// **Safety invariant.** The raw EIP-2718 envelope is built against a
/// *predicted* post-oracle-update state. That prediction may never
/// materialise: the triggering oracle tx can revert, get replaced via
/// an EIP-1559 bump, or simply not land in the next block. Callers
/// MUST re-simulate the raw tx against confirmed block state before
/// broadcasting, per the CLAUDE.md hard invariant "every liquidation
/// transaction passes an eth_call simulation gate before broadcast".
///
/// The cache enforces this structurally: [`PendingCache::drain`]
/// returns [`UnverifiedPreSigned`] wrappers rather than
/// `PreSignedLiquidation` directly. The raw tx is only reachable via
/// [`UnverifiedPreSigned::verify`], which demands a
/// [`SimulationVerdict::Ok`] proof token that only a just-passed
/// simulation can produce.
#[derive(Debug, Clone)]
pub struct PreSignedLiquidation {
    /// Borrower targeted. Also the map key; duplicated here so a
    /// drained `Vec<PreSignedLiquidation>` is self-describing.
    pub borrower: Address,
    /// Raw EIP-2718 envelope bytes, as produced by
    /// [`TxBuilder::sign`](charon_executor::TxBuilder::sign). Ready
    /// for `eth_sendRawTransaction`.
    ///
    /// **Intentionally pub-but-guarded.** The field is public so
    /// in-process construction stays ergonomic (tests, the mempool's
    /// own insert path) but the drain API never hands a
    /// `PreSignedLiquidation` to the broadcaster — it hands an
    /// [`UnverifiedPreSigned`] so the simulation gate cannot be
    /// bypassed at the type layer.
    pub raw_tx: Bytes,
    /// The opportunity this tx was built against. Carried so the
    /// drainer can log context and re-rank if multiple pre-signs
    /// target the same borrower across different oracle updates.
    pub opportunity: LiquidationOpportunity,
    /// Hash of the pending oracle tx that motivated this pre-sign.
    pub trigger_tx: B256,
    /// Unix seconds at which the entry was inserted.
    pub inserted_at: u64,
}

/// Proof token that an `eth_call` simulation against current block
/// state accepted the candidate tx. Produced only by code that has
/// actually run the simulator — `Ok` has no public constructor beyond
/// [`SimulationVerdict::approve`], so a broadcaster cannot fabricate
/// one.
#[derive(Debug, Clone, Copy)]
#[must_use = "a verdict of Revert or Error must short-circuit the broadcast"]
pub enum SimulationVerdict {
    /// The simulator returned a success receipt; the tx is safe to
    /// broadcast against the block the simulator saw.
    ///
    /// **Construction rule.** `Ok` is literal-constructible by any
    /// in-crate caller, but by convention only simulator boundary code
    /// (or [`SimulationVerdict::approve`]) should emit it. Any other
    /// call site producing `SimulationVerdict::Ok` is a review flag —
    /// reviewers should reject it unless it is demonstrably tied to a
    /// real `eth_call` outcome. Sealing would require a cross-crate
    /// proof-token type that the executor does not yet expose.
    Ok,
    /// The simulator returned a reverting receipt. The tx must not
    /// be broadcast.
    Revert,
    /// The simulator itself errored (RPC timeout, encoding bug). Treat
    /// as Revert for safety.
    Error,
}

impl SimulationVerdict {
    /// Narrow constructor kept alongside the enum so every
    /// `SimulationVerdict::Ok` at a call site is traceable to a
    /// simulator outcome, not a hand-rolled literal.
    pub fn approve() -> Self {
        SimulationVerdict::Ok
    }
}

/// Newtype returned by [`PendingCache::drain`]. Wraps a
/// `PreSignedLiquidation` so the raw EIP-2718 envelope is only
/// reachable after the caller presents a passing
/// [`SimulationVerdict`]. Honours the CLAUDE.md safety invariant that
/// every liquidation tx must pass an `eth_call` gate before broadcast,
/// enforced by the type system instead of a comment.
#[derive(Debug, Clone)]
#[must_use = "pre-signs bypass the executor's eth_call gate; call .verify(simulation_verdict) before broadcasting"]
pub struct UnverifiedPreSigned {
    inner: PreSignedLiquidation,
}

impl UnverifiedPreSigned {
    /// Peek at the borrower without unwrapping the raw tx — lets the
    /// drain-site log context and rank candidates before simulation.
    pub fn borrower(&self) -> Address {
        self.inner.borrower
    }

    /// Peek at the trigger oracle tx hash.
    pub fn trigger_tx(&self) -> B256 {
        self.inner.trigger_tx
    }

    /// Peek at the opportunity payload so callers can feed it to the
    /// simulator without consuming the wrapper.
    pub fn opportunity(&self) -> &LiquidationOpportunity {
        &self.inner.opportunity
    }

    /// Consume the wrapper and return the raw tx + metadata ONLY when
    /// the caller presents a passing simulation verdict. A `Revert` or
    /// `Error` verdict returns `Err((self, verdict))` so the caller
    /// keeps the wrapper for logging and cannot accidentally broadcast.
    ///
    /// The `Err` variant is intentionally as heavy as the `Ok` variant
    /// (both carry the full `PreSignedLiquidation`) — returning the
    /// wrapper by value is what preserves the type-level guarantee that
    /// the raw tx is never reachable without a passing verdict. Boxing
    /// the error would only obscure the shape without meaningful win on
    /// the non-broadcast path.
    #[allow(clippy::result_large_err)]
    pub fn verify(
        self,
        verdict: SimulationVerdict,
    ) -> std::result::Result<PreSignedLiquidation, (Self, SimulationVerdict)> {
        match verdict {
            SimulationVerdict::Ok => Ok(self.inner),
            SimulationVerdict::Revert | SimulationVerdict::Error => Err((self, verdict)),
        }
    }
}

/// Pure decode + pre-sign storage. Separated from the RPC layer so
/// tests can exercise the selector logic and TTL semantics without
/// opening a socket.
#[derive(Debug)]
pub struct PendingCache {
    oracle: Address,
    selectors: HashSet<FixedBytes<4>>,
    pending: DashMap<Address, PreSignedLiquidation>,
    max_pending_age_secs: u64,
}

impl PendingCache {
    pub fn new(
        oracle: Address,
        selectors: HashSet<FixedBytes<4>>,
        max_pending_age: Duration,
    ) -> Self {
        Self {
            oracle,
            selectors,
            pending: DashMap::new(),
            max_pending_age_secs: max_pending_age.as_secs(),
        }
    }

    pub fn with_defaults(oracle: Address) -> Self {
        Self::new(oracle, default_selectors(), DEFAULT_MAX_PENDING_AGE)
    }

    pub fn oracle(&self) -> Address {
        self.oracle
    }

    pub fn is_tracked_selector(&self, selector: FixedBytes<4>) -> bool {
        self.selectors.contains(&selector)
    }

    /// Insert a freshly pre-signed liquidation. Overwrites any prior
    /// entry for the same borrower — the most recent oracle update
    /// wins, which is what we want when two updates land in the same
    /// block window (the later one is what the chain will see).
    pub fn insert(&self, tx: PreSignedLiquidation) {
        debug!(
            borrower = %tx.borrower,
            trigger = %tx.trigger_tx,
            "pre-signed liquidation armed"
        );
        self.pending.insert(tx.borrower, tx);
    }

    pub fn pending_len(&self) -> usize {
        self.pending.len()
    }

    pub fn is_empty(&self) -> bool {
        self.pending.is_empty()
    }

    /// Take every entry out of the pending map and drop any that are
    /// older than `max_pending_age_secs`. Called by the block-listener
    /// task on each `NewBlock` event — pre-signs only live for one
    /// block window, so anything that didn't fire is stale.
    ///
    /// Each returned [`UnverifiedPreSigned`] requires a
    /// [`SimulationVerdict::Ok`] from the caller before its raw tx is
    /// reachable. This mirrors the CLAUDE.md safety invariant in the
    /// type system: a broadcaster written against this API cannot
    /// skip the `eth_call` gate without disabling the type checker.
    #[must_use = "dropping the drained vec discards pre-signs without broadcasting; at minimum log and re-insert"]
    pub fn drain(&self) -> Vec<UnverifiedPreSigned> {
        let now = unix_now();
        let max_age = self.max_pending_age_secs;
        let mut out = Vec::with_capacity(self.pending.len());
        let keys: Vec<Address> = self.pending.iter().map(|e| *e.key()).collect();
        for k in keys {
            if let Some((_, entry)) = self.pending.remove(&k) {
                if now.saturating_sub(entry.inserted_at) > max_age {
                    warn!(
                        borrower = %entry.borrower,
                        age_secs = now.saturating_sub(entry.inserted_at),
                        "dropped stale pre-signed liquidation"
                    );
                    continue;
                }
                out.push(UnverifiedPreSigned { inner: entry });
            }
        }
        debug!(drained = out.len(), "mempool cache drained");
        out
    }

    /// Pure decoder — returns `None` when the recipient isn't the
    /// bound oracle, the selector isn't tracked, or the calldata
    /// fails to decode against every candidate shape.
    pub fn decode(&self, tx_hash: B256, to: Option<Address>, input: &[u8]) -> Option<OracleUpdate> {
        if to != Some(self.oracle) {
            return None;
        }
        if input.len() < 4 {
            return None;
        }
        let selector = FixedBytes::<4>::from_slice(&input[..4]);
        if !self.selectors.contains(&selector) {
            return None;
        }
        decode_oracle_call(tx_hash, selector, input)
    }
}

/// Subscribes to the pending-tx stream, filters oracle updates, and
/// holds pre-signed liquidations until the next block.
///
/// Cheap to clone — all mutable state lives behind `Arc` / `DashMap`.
/// Clone into the block-listener task so it can call
/// [`MempoolMonitor::drain`] without coordinating with the mempool
/// task.
#[derive(Clone)]
pub struct MempoolMonitor {
    provider: Arc<RootProvider<PubSubFrontend>>,
    cache: Arc<PendingCache>,
}

impl MempoolMonitor {
    /// Full-control constructor.
    pub fn new(
        provider: Arc<RootProvider<PubSubFrontend>>,
        oracle: Address,
        selectors: HashSet<FixedBytes<4>>,
        max_pending_age: Duration,
    ) -> Self {
        Self {
            provider,
            cache: Arc::new(PendingCache::new(oracle, selectors, max_pending_age)),
        }
    }

    /// Convenience: build with [`default_selectors`] and
    /// [`DEFAULT_MAX_PENDING_AGE`].
    pub fn with_defaults(provider: Arc<RootProvider<PubSubFrontend>>, oracle: Address) -> Self {
        Self::new(
            provider,
            oracle,
            default_selectors(),
            DEFAULT_MAX_PENDING_AGE,
        )
    }

    pub fn oracle(&self) -> Address {
        self.cache.oracle()
    }

    /// Share the inner cache. Lets the block-listener task call
    /// [`PendingCache::drain`] without going through the monitor,
    /// which keeps its `run` loop free to stay on the pending-tx
    /// stream.
    pub fn cache(&self) -> Arc<PendingCache> {
        self.cache.clone()
    }

    pub fn insert(&self, tx: PreSignedLiquidation) {
        self.cache.insert(tx);
    }

    #[must_use = "dropping the drained vec discards pre-signs without broadcasting; at minimum log and re-insert"]
    pub fn drain(&self) -> Vec<UnverifiedPreSigned> {
        self.cache.drain()
    }

    pub fn pending_len(&self) -> usize {
        self.cache.pending_len()
    }

    /// Run the pending-tx subscription forever. Reconnect on stream
    /// error with the same 1 s → 30 s exponential backoff as
    /// [`BlockListener`](crate::listener::BlockListener).
    ///
    /// Emits one [`OracleUpdate`] per matched tx on `tx`. Returns
    /// `Ok(())` only when the receiver is dropped — the loop is
    /// expected to run for the lifetime of the process.
    pub async fn run(&self, tx: mpsc::Sender<OracleUpdate>) -> Result<()> {
        let mut backoff = Duration::from_secs(1);
        loop {
            match self.run_once(&tx).await {
                Ok(()) => {
                    info!(oracle = %self.oracle(), "mempool channel closed, exiting");
                    return Ok(());
                }
                Err(err) => {
                    warn!(
                        oracle = %self.oracle(),
                        error = ?err,
                        backoff_secs = backoff.as_secs(),
                        "mempool subscription error, reconnecting after backoff"
                    );
                    tokio::time::sleep(backoff).await;
                    backoff = (backoff * 2).min(Duration::from_secs(30));
                }
            }
        }
    }

    async fn run_once(&self, tx: &mpsc::Sender<OracleUpdate>) -> Result<()> {
        let sub = self
            .provider
            .subscribe_pending_transactions()
            .await
            .context("mempool: subscribe_pending_transactions failed")?;

        info!(oracle = %self.oracle(), "pending-tx subscription established");

        let mut stream = sub.into_stream();

        // First-tx watchdog. If the configured endpoint silently drops
        // `newPendingTransactions` (every public BSC RPC) the
        // subscription call above still succeeds but the stream never
        // yields. Nudge the operator at `FIRST_TX_WATCHDOG` with a
        // diagnosis pointing at the likely cause.
        let mut saw_first_tx = false;
        let mut watchdog =
            Box::pin(tokio::time::sleep(FIRST_TX_WATCHDOG));

        loop {
            tokio::select! {
                biased;
                maybe_hash = stream.next() => {
                    let Some(hash) = maybe_hash else { break; };
                    if !saw_first_tx {
                        saw_first_tx = true;
                        debug!(%hash, "first pending tx received, watchdog disarmed");
                    }
                    if !self.handle_pending_hash(hash, tx).await? {
                        return Ok(());
                    }
                }
                _ = &mut watchdog, if !saw_first_tx => {
                    warn!(
                        oracle = %self.oracle(),
                        watchdog_secs = FIRST_TX_WATCHDOG.as_secs(),
                        "no pending tx received after subscribe — the endpoint is likely a public RPC that disables newPendingTransactions or exposes only its local pool. MempoolMonitor requires a paid MEV stream (bloxroute/blocknative) or a self-hosted BSC geth with the txpool exposed. See module docs."
                    );
                }
            }
        }

        anyhow::bail!("mempool: pending-tx subscription stream ended")
    }

    /// Look up a pending tx hash, decode it, and forward any decoded
    /// [`OracleUpdate`] on `tx`. Returns `Ok(false)` when the receiver
    /// has been dropped (caller should exit cleanly), `Ok(true)`
    /// otherwise. Extracted from `run_once` so the watchdog loop stays
    /// readable.
    async fn handle_pending_hash(
        &self,
        hash: B256,
        tx: &mpsc::Sender<OracleUpdate>,
    ) -> Result<bool> {
        // Lookup failures are common for txs that dropped out of the
        // pool between the hash push and our get — log at debug, keep
        // going.
        let full = match self.provider.get_transaction_by_hash(hash).await {
            Ok(Some(t)) => t,
            Ok(None) => {
                debug!(%hash, "pending tx vanished before fetch");
                return Ok(true);
            }
            Err(err) => {
                debug!(%hash, ?err, "get_transaction_by_hash failed");
                return Ok(true);
            }
        };

        let to = full.inner.kind().to().copied();
        let input = full.inner.input();
        let Some(update) = self.cache.decode(hash, to, input) else {
            return Ok(true);
        };

        info!(
            %hash,
            asset = %update.asset,
            selector = %format_selector(update.selector),
            price = ?update.new_price,
            "venus oracle update seen in mempool"
        );

        if tx.send(update).await.is_err() {
            return Ok(false);
        }
        Ok(true)
    }
}

/// The four Venus oracle write selectors this module recognises by
/// default. Callers can override via [`MempoolMonitor::new`] — for
/// example to track a chain-specific proxy that exposes a different
/// setter name.
pub fn default_selectors() -> HashSet<FixedBytes<4>> {
    let mut s = HashSet::with_capacity(4);
    s.insert(IVenusOracleWrite::updatePriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::updateAssetPriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::setDirectPriceCall::SELECTOR.into());
    s.insert(IVenusOracleWrite::setUnderlyingPriceCall::SELECTOR.into());
    s
}

fn decode_oracle_call(
    tx_hash: B256,
    selector: FixedBytes<4>,
    input: &[u8],
) -> Option<OracleUpdate> {
    // `abi_decode_raw` skips the selector and validates the body.
    // `validate = true` rejects trailing junk.
    let body = &input[4..];

    if selector == FixedBytes::<4>::from(IVenusOracleWrite::updatePriceCall::SELECTOR) {
        let call = IVenusOracleWrite::updatePriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: None,
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::updateAssetPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::updateAssetPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: None,
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::setDirectPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::setDirectPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.asset,
            new_price: Some(call.price),
        });
    }
    if selector == FixedBytes::<4>::from(IVenusOracleWrite::setUnderlyingPriceCall::SELECTOR) {
        let call = IVenusOracleWrite::setUnderlyingPriceCall::abi_decode_raw(body, true).ok()?;
        return Some(OracleUpdate {
            tx_hash,
            selector,
            asset: call.vToken,
            new_price: Some(call.price),
        });
    }
    None
}

fn format_selector(sel: FixedBytes<4>) -> String {
    let b = sel.as_slice();
    format!("0x{:02x}{:02x}{:02x}{:02x}", b[0], b[1], b[2], b[3])
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::{address, b256};
    use alloy::sol_types::SolCall;
    use charon_core::{FlashLoanSource, Position, ProtocolId, SwapRoute};

    const ORACLE: Address = address!("1111111111111111111111111111111111111111");
    const OTHER: Address = address!("2222222222222222222222222222222222222222");
    const ASSET: Address = address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    const HASH: B256 = b256!("abababababababababababababababababababababababababababababababab");

    fn mk_cache() -> PendingCache {
        PendingCache::with_defaults(ORACLE)
    }

    fn mk_opp() -> LiquidationOpportunity {
        LiquidationOpportunity {
            position: Position {
                protocol: ProtocolId::Venus,
                chain_id: 56,
                borrower: address!("3333333333333333333333333333333333333333"),
                collateral_token: address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
                debt_token: address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
                collateral_amount: U256::from(1_000u64),
                debt_amount: U256::from(500u64),
                health_factor: U256::ZERO,
                liquidation_bonus_bps: 1_000,
            },
            debt_to_repay: U256::from(250u64),
            expected_collateral_out: U256::from(275u64),
            flash_source: FlashLoanSource::AaveV3,
            swap_route: SwapRoute {
                token_in: address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
                token_out: address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
                amount_in: U256::from(275u64),
                min_amount_out: U256::from(260u64),
                pool_fee: 3_000,
            },
            net_profit_usd_cents: 5_000,
        }
    }

    #[test]
    fn default_selectors_has_four_entries() {
        assert_eq!(default_selectors().len(), 4);
    }

    #[test]
    fn decode_update_price_yields_asset_without_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updatePriceCall { asset: ASSET };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert!(out.new_price.is_none());
        assert_eq!(out.tx_hash, HASH);
    }

    #[test]
    fn decode_update_asset_price_yields_asset_without_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updateAssetPriceCall { asset: ASSET };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert!(out.new_price.is_none());
    }

    #[test]
    fn decode_set_direct_price_carries_new_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::setDirectPriceCall {
            asset: ASSET,
            price: U256::from(12_345u64),
        };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert_eq!(out.new_price, Some(U256::from(12_345u64)));
    }

    #[test]
    fn decode_set_underlying_price_carries_vtoken_and_price() {
        let c = mk_cache();
        let call = IVenusOracleWrite::setUnderlyingPriceCall {
            vToken: ASSET,
            price: U256::from(99u64),
        };
        let data = call.abi_encode();
        let out = c.decode(HASH, Some(ORACLE), &data).expect("match");
        assert_eq!(out.asset, ASSET);
        assert_eq!(out.new_price, Some(U256::from(99u64)));
    }

    #[test]
    fn decode_rejects_wrong_recipient() {
        let c = mk_cache();
        let call = IVenusOracleWrite::updatePriceCall { asset: ASSET };
        let data = call.abi_encode();
        assert!(c.decode(HASH, Some(OTHER), &data).is_none());
        assert!(c.decode(HASH, None, &data).is_none());
    }

    #[test]
    fn decode_rejects_unknown_selector() {
        let c = mk_cache();
        // `transfer(address,uint256)` selector — not in the tracked
        // set. Followed by two zero-padded words so a lenient decoder
        // wouldn't accidentally accept it.
        let mut data = vec![0xa9, 0x05, 0x9c, 0xbb];
        data.extend_from_slice(&[0u8; 64]);
        assert!(c.decode(HASH, Some(ORACLE), &data).is_none());
    }

    #[test]
    fn decode_rejects_short_input() {
        let c = mk_cache();
        assert!(c.decode(HASH, Some(ORACLE), &[]).is_none());
        assert!(c.decode(HASH, Some(ORACLE), &[0xde, 0xad]).is_none());
    }

    #[test]
    fn decode_rejects_truncated_calldata() {
        let c = mk_cache();
        let sel: [u8; 4] = IVenusOracleWrite::updatePriceCall::SELECTOR;
        assert!(c.decode(HASH, Some(ORACLE), &sel).is_none());
    }

    #[test]
    fn insert_and_drain_roundtrips() {
        let c = mk_cache();
        let opp = mk_opp();
        let borrower = opp.position.borrower;
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x01, 0x02, 0x03]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert_eq!(drained.len(), 1);
        assert_eq!(drained[0].borrower(), borrower);
        assert_eq!(c.pending_len(), 0);
        // Second drain yields nothing.
        assert!(c.drain().is_empty());
    }

    #[test]
    fn drain_drops_stale_entries() {
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::new(),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now().saturating_sub(3_600),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert!(drained.is_empty(), "stale entry should be dropped");
        assert_eq!(c.pending_len(), 0);
    }

    #[test]
    fn insert_overwrites_same_borrower() {
        let c = mk_cache();
        let opp = mk_opp();
        let borrower = opp.position.borrower;
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x01]),
            opportunity: opp.clone(),
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        c.insert(PreSignedLiquidation {
            borrower,
            raw_tx: Bytes::from_static(&[0x02]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        assert_eq!(c.pending_len(), 1);
        let drained = c.drain();
        assert_eq!(drained.len(), 1);
        // To read raw_tx the caller must present a passing verdict —
        // that's the whole point of the wrapper (see #226).
        let unwrapped = drained
            .into_iter()
            .next()
            .unwrap()
            .verify(SimulationVerdict::approve())
            .expect("approved verdict must unwrap");
        assert_eq!(unwrapped.raw_tx.as_ref(), &[0x02]);
    }

    #[test]
    fn verify_ok_returns_inner_signed() {
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::from_static(&[0xaa]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        let drained = c.drain();
        let verified = drained
            .into_iter()
            .next()
            .unwrap()
            .verify(SimulationVerdict::Ok)
            .expect("Ok verdict unwraps");
        assert_eq!(verified.raw_tx.as_ref(), &[0xaa]);
    }

    #[test]
    fn verify_revert_keeps_wrapper_and_hides_raw_tx() {
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::from_static(&[0xbb]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        let drained = c.drain();
        let wrapped = drained.into_iter().next().unwrap();
        let borrower_before = wrapped.borrower();
        match wrapped.verify(SimulationVerdict::Revert) {
            Err((still_wrapped, v)) => {
                assert!(matches!(v, SimulationVerdict::Revert));
                assert_eq!(still_wrapped.borrower(), borrower_before);
            }
            Ok(_) => panic!("Revert must not unwrap"),
        }
    }

    #[test]
    fn verify_revert_then_ok_roundtrips() {
        // A rejected verdict must leave the wrapper usable for a retry
        // simulation. Without this, a transient RPC error on the first
        // simulate would permanently strand the pre-sign.
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::from_static(&[0xdd]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        let wrapped = c.drain().into_iter().next().unwrap();
        let (retry, _) = match wrapped.verify(SimulationVerdict::Revert) {
            Err(pair) => pair,
            Ok(_) => panic!("Revert must not unwrap"),
        };
        let verified = retry
            .verify(SimulationVerdict::Ok)
            .expect("retry with Ok must unwrap");
        assert_eq!(verified.raw_tx.as_ref(), &[0xdd]);
    }

    #[test]
    fn peek_accessors_survive_failed_verify() {
        // Confirm every read-only accessor is still reachable on the
        // wrapper after a failed verdict — the logging/ranking path
        // must not be blocked by the failure.
        let c = mk_cache();
        let opp = mk_opp();
        let borrower_expected = opp.position.borrower;
        c.insert(PreSignedLiquidation {
            borrower: borrower_expected,
            raw_tx: Bytes::from_static(&[0xee]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        let wrapped = c.drain().into_iter().next().unwrap();
        let (still_wrapped, _) = match wrapped.verify(SimulationVerdict::Error) {
            Err(pair) => pair,
            Ok(_) => panic!("Error must not unwrap"),
        };
        assert_eq!(still_wrapped.borrower(), borrower_expected);
        assert_eq!(still_wrapped.trigger_tx(), HASH);
        assert_eq!(still_wrapped.opportunity().position.borrower, borrower_expected);
    }

    #[test]
    fn verify_error_keeps_wrapper_and_hides_raw_tx() {
        let c = mk_cache();
        let opp = mk_opp();
        c.insert(PreSignedLiquidation {
            borrower: opp.position.borrower,
            raw_tx: Bytes::from_static(&[0xcc]),
            opportunity: opp,
            trigger_tx: HASH,
            inserted_at: unix_now(),
        });
        let drained = c.drain();
        let wrapped = drained.into_iter().next().unwrap();
        assert!(matches!(
            wrapped.verify(SimulationVerdict::Error),
            Err((_, SimulationVerdict::Error))
        ));
    }

    #[test]
    fn is_tracked_selector_matches_defaults() {
        let c = mk_cache();
        let sel = FixedBytes::<4>::from(IVenusOracleWrite::updatePriceCall::SELECTOR);
        assert!(c.is_tracked_selector(sel));
        let unknown = FixedBytes::<4>::from([0xde, 0xad, 0xbe, 0xef]);
        assert!(!c.is_tracked_selector(unknown));
    }

    #[test]
    fn oracle_round_trips() {
        let c = mk_cache();
        assert_eq!(c.oracle(), ORACLE);
    }

    #[test]
    fn format_selector_renders_lowercase_hex() {
        let sel = FixedBytes::<4>::from([0xab, 0xcd, 0xef, 0x01]);
        assert_eq!(format_selector(sel), "0xabcdef01");
    }
}
